language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
# command to run tests
script:
#  - pytest -v # or py.test for Python versions 3.5 and below
  - py.test -v # or py.test for Python versions 3.5 and below
